include: package:lint/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_bool_literals_in_conditional_expressions: false
    sort_pub_dependencies: false